detect_ball_3d:
  ros__parameters:
    h_fov: 1.089
    ball_radius: 0.033
    camera_frame: "camera_link_optical"

follow_ball:
  ros__parameters:
    rcv_timeout_secs: 1.0
    angular_chase_multiplier: 0.7
    forward_chase_speed: 0.1
    search_angular_speed: 0.5
    max_size_thresh: 0.1
    filter_value: 0.9